import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/XinYi Jiang/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.argv[2]||'末日学校-抵达后互动-第一顿饭-20260930-v1',out=path.resolve('qa',base);
await fs.mkdir(out,{recursive:true});
const scenes=JSON.parse(await fs.readFile(path.resolve('drafts',base+'.json'),'utf8'));
const expected=scenes.flatMap(s=>s.rows.map(r=>r[2]));
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],network=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url())});
try{
 await page.goto(pathToFileURL(path.resolve('drafts',base+'.html')).href);
 await page.addStyleTag({content:'html{scroll-behavior:auto!important}'});
 assert.deepEqual(await page.locator('.source').allTextContents(),expected);
 assert.equal(await page.locator('.scene').count(),scenes.length);
 assert.equal(await page.locator('.role').count(),6);
 const speakers=await page.locator('.spoken .badge').allTextContents();
 assert.deepEqual([...new Set(speakers)].sort(),['G','N1','N2','N3','N4']);
 assert.equal(await page.locator('.pid').first().textContent(),'I001');
 await page.locator('[data-role="o"]').click();
 assert.ok(await page.locator('.dimmed').count()>0);
 await page.locator('#search').fill('密码');
 assert.ok(await page.locator('.entry:visible').count()>0);
 assert.ok(await page.locator('.entry:visible').count()<expected.length);
 await page.locator('#search').fill('不存在123456');
 assert.equal(await page.locator('#empty').isVisible(),true);
 await page.locator('#reset').click();
 await page.locator('#directions').uncheck();
 assert.equal(await page.locator('.stage:visible').count(),0);
 await page.locator('#reset').click();
 await page.locator('.director summary').click();
 assert.equal(await page.locator('.director').getAttribute('open'),'');
 await page.locator('.director summary').click();
 await page.screenshot({path:path.join(out,'desktop.png')});
 await page.locator('a[href="#scene-2"]').click();
 await page.screenshot({path:path.join(out,'meal.png')});
 for(const width of [1440,768,390]){
  await page.setViewportSize({width,height:1000});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false,'overflow '+width);
 }
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:path.join(out,'mobile.png')});
 assert.deepEqual(errors,[]);assert.deepEqual(network,[]);
 await fs.writeFile(path.join(out,'report.json'),JSON.stringify({entries:expected.length,scenes:scenes.length,onlyFiveNPCSpeakers:true,sourceExact:true,controlsPassed:true,viewportWidths:[1440,768,390],errors,externalRequests:network},null,2));
 console.log(`${expected.length} entries, ${scenes.length} scenes, only G/N1/N2/N3/N4 speak; text, controls and layouts verified.`);
}finally{await browser.close()}
